package com.kodilla.exception.main;


import com.kodilla.exception.test.FirstChallenge;

public class ExceptionModuleRunner {
    /**
     * This main can throw an ArithmeticException!!!
     * @param args
     */
    public static void main(String[] args) {
        FirstChallenge firstChallenge = new FirstChallenge();
        double result = firstChallenge.divide(3, 0);

        System.out.println(result);
    }
}



